[package]
authors = [
    "Georg Semmler <georg_semmler_05@web.de>",
    "Janosch Gräf <janosch.graef@cispa-helmholtz.de>"
]
name = "diesel-custom-type"
version = "1.3.3"

[dependencies]
diesel = "1.3.3"
